// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ProtoFixed.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 固定靠前的消息cmd messageid生成先读取这个文件
// 信息提示
type CSMessageCodeRsp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSMessageCodeRsp) Reset()         { *m = CSMessageCodeRsp{} }
func (m *CSMessageCodeRsp) String() string { return proto.CompactTextString(m) }
func (*CSMessageCodeRsp) ProtoMessage()    {}
func (*CSMessageCodeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_397221bf3266f005, []int{0}
}

func (m *CSMessageCodeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSMessageCodeRsp.Unmarshal(m, b)
}
func (m *CSMessageCodeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSMessageCodeRsp.Marshal(b, m, deterministic)
}
func (m *CSMessageCodeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSMessageCodeRsp.Merge(m, src)
}
func (m *CSMessageCodeRsp) XXX_Size() int {
	return xxx_messageInfo_CSMessageCodeRsp.Size(m)
}
func (m *CSMessageCodeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CSMessageCodeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CSMessageCodeRsp proto.InternalMessageInfo

func (m *CSMessageCodeRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// 重连
type CSReconnectReq struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Flag                 uint32   `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSReconnectReq) Reset()         { *m = CSReconnectReq{} }
func (m *CSReconnectReq) String() string { return proto.CompactTextString(m) }
func (*CSReconnectReq) ProtoMessage()    {}
func (*CSReconnectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_397221bf3266f005, []int{1}
}

func (m *CSReconnectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSReconnectReq.Unmarshal(m, b)
}
func (m *CSReconnectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSReconnectReq.Marshal(b, m, deterministic)
}
func (m *CSReconnectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSReconnectReq.Merge(m, src)
}
func (m *CSReconnectReq) XXX_Size() int {
	return xxx_messageInfo_CSReconnectReq.Size(m)
}
func (m *CSReconnectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CSReconnectReq.DiscardUnknown(m)
}

var xxx_messageInfo_CSReconnectReq proto.InternalMessageInfo

func (m *CSReconnectReq) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CSReconnectReq) GetFlag() uint32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

// 登陆请求
type CSLoginReq struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ProtoNum             int32    `protobuf:"varint,2,opt,name=ProtoNum,proto3" json:"ProtoNum,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Account              string   `protobuf:"bytes,4,opt,name=Account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSLoginReq) Reset()         { *m = CSLoginReq{} }
func (m *CSLoginReq) String() string { return proto.CompactTextString(m) }
func (*CSLoginReq) ProtoMessage()    {}
func (*CSLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_397221bf3266f005, []int{2}
}

func (m *CSLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSLoginReq.Unmarshal(m, b)
}
func (m *CSLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSLoginReq.Marshal(b, m, deterministic)
}
func (m *CSLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSLoginReq.Merge(m, src)
}
func (m *CSLoginReq) XXX_Size() int {
	return xxx_messageInfo_CSLoginReq.Size(m)
}
func (m *CSLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CSLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_CSLoginReq proto.InternalMessageInfo

func (m *CSLoginReq) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CSLoginReq) GetProtoNum() int32 {
	if m != nil {
		return m.ProtoNum
	}
	return 0
}

func (m *CSLoginReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CSLoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// 创建角色请求
type CSCreateRoleReq struct {
	Uid                  uint32   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSCreateRoleReq) Reset()         { *m = CSCreateRoleReq{} }
func (m *CSCreateRoleReq) String() string { return proto.CompactTextString(m) }
func (*CSCreateRoleReq) ProtoMessage()    {}
func (*CSCreateRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_397221bf3266f005, []int{3}
}

func (m *CSCreateRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSCreateRoleReq.Unmarshal(m, b)
}
func (m *CSCreateRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSCreateRoleReq.Marshal(b, m, deterministic)
}
func (m *CSCreateRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSCreateRoleReq.Merge(m, src)
}
func (m *CSCreateRoleReq) XXX_Size() int {
	return xxx_messageInfo_CSCreateRoleReq.Size(m)
}
func (m *CSCreateRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CSCreateRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_CSCreateRoleReq proto.InternalMessageInfo

func (m *CSCreateRoleReq) GetUid() uint32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CSCreateRoleReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

// GM命令用于调试
type CSGmCmdReq struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSGmCmdReq) Reset()         { *m = CSGmCmdReq{} }
func (m *CSGmCmdReq) String() string { return proto.CompactTextString(m) }
func (*CSGmCmdReq) ProtoMessage()    {}
func (*CSGmCmdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_397221bf3266f005, []int{4}
}

func (m *CSGmCmdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSGmCmdReq.Unmarshal(m, b)
}
func (m *CSGmCmdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSGmCmdReq.Marshal(b, m, deterministic)
}
func (m *CSGmCmdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSGmCmdReq.Merge(m, src)
}
func (m *CSGmCmdReq) XXX_Size() int {
	return xxx_messageInfo_CSGmCmdReq.Size(m)
}
func (m *CSGmCmdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CSGmCmdReq.DiscardUnknown(m)
}

var xxx_messageInfo_CSGmCmdReq proto.InternalMessageInfo

func (m *CSGmCmdReq) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func init() {
	proto.RegisterType((*CSMessageCodeRsp)(nil), "pb.CSMessageCodeRsp")
	proto.RegisterType((*CSReconnectReq)(nil), "pb.CSReconnectReq")
	proto.RegisterType((*CSLoginReq)(nil), "pb.CSLoginReq")
	proto.RegisterType((*CSCreateRoleReq)(nil), "pb.CSCreateRoleReq")
	proto.RegisterType((*CSGmCmdReq)(nil), "pb.CSGmCmdReq")
}

func init() { proto.RegisterFile("ProtoFixed.proto", fileDescriptor_397221bf3266f005) }

var fileDescriptor_397221bf3266f005 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0x33, 0x31,
	0x10, 0x40, 0xd9, 0xb6, 0xfb, 0x7d, 0xee, 0x80, 0xba, 0x04, 0x0f, 0xc1, 0x83, 0x94, 0x1c, 0xa4,
	0x27, 0x2f, 0x82, 0x57, 0x91, 0x80, 0x5e, 0xb4, 0xc8, 0xec, 0x2f, 0xd8, 0x26, 0xe3, 0xb2, 0xb6,
	0xc9, 0xac, 0xdd, 0x2c, 0xf8, 0xf3, 0x25, 0x53, 0xed, 0x49, 0x6f, 0xef, 0x0d, 0x79, 0xcc, 0x10,
	0xa8, 0x5f, 0xf7, 0x9c, 0xf8, 0xb1, 0xff, 0x24, 0x7f, 0x33, 0x64, 0x54, 0xb3, 0x61, 0x63, 0xae,
	0xa1, 0xb6, 0xcd, 0x0b, 0x8d, 0x63, 0xdb, 0x91, 0x65, 0x4f, 0x38, 0x0e, 0x4a, 0xc1, 0xc2, 0xb1,
	0x27, 0x5d, 0x2c, 0x8b, 0x55, 0x89, 0xc2, 0xe6, 0x0e, 0xce, 0x6c, 0x83, 0xe4, 0x38, 0x46, 0x72,
	0x09, 0xe9, 0x43, 0xd5, 0x30, 0x9f, 0x7a, 0x2f, 0x8f, 0x4e, 0x31, 0x63, 0xee, 0xde, 0x76, 0x6d,
	0xa7, 0x67, 0x32, 0x12, 0x36, 0xef, 0x00, 0xb6, 0x79, 0xe6, 0xae, 0x8f, 0xbf, 0x37, 0x97, 0x70,
	0x22, 0x77, 0xad, 0xa7, 0x20, 0x5d, 0x89, 0x47, 0x57, 0x17, 0x50, 0x26, 0xde, 0x52, 0xd4, 0xf3,
	0x65, 0xb1, 0xaa, 0xf0, 0x20, 0x4a, 0xc3, 0xff, 0x07, 0xe7, 0x78, 0x8a, 0x49, 0x2f, 0x64, 0xfe,
	0xa3, 0xe6, 0x1e, 0xce, 0x6d, 0x63, 0xf7, 0xd4, 0x26, 0x42, 0xde, 0xd1, 0x9f, 0x0b, 0x63, 0xef,
	0xb6, 0xeb, 0x36, 0x90, 0x2c, 0xac, 0xf0, 0xe8, 0xe6, 0x2a, 0x1f, 0xfb, 0x14, 0x6c, 0xf0, 0xdf,
	0xad, 0x0b, 0x87, 0xb6, 0xc2, 0x8c, 0x9b, 0x7f, 0xf2, 0x6f, 0xb7, 0x5f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x16, 0xc3, 0x04, 0x75, 0x4b, 0x01, 0x00, 0x00,
}
